name: Database Setup

on:
  workflow_dispatch:
  push:
    paths:
      - '**.sql'

jobs:
  setup-database:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: immucare_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Verify MySQL connection
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "SHOW DATABASES"
      
      - name: Import initial database schema
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root immucare_db < setup_database.sql
      
      - name: Import main database data
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root immucare_db < immucare_db.sql
      
      - name: Apply database updates
        run: |
          if [ -f update_appointments_table.sql ]; then
            mysql --host=127.0.0.1 --port=3306 --user=root --password=root immucare_db < update_appointments_table.sql
          fi
          if [ -f update_sms_logs_table.sql ]; then
            mysql --host=127.0.0.1 --port=3306 --user=root --password=root immucare_db < update_sms_logs_table.sql
          fi
      
      - name: Verify database structure
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root -e "USE immucare_db; SHOW TABLES;" 