name: Security Scans

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Update dependencies
        run: |
          composer require maennchen/zipstream-php:^2.4 --with-all-dependencies --no-interaction

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP Security Scanner
        uses: symfonycorp/security-checker-action@v4

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://your-staging-url.example.com'
          fail_action: false
          cmd_options: '-a'

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3

  code-scanning:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, php

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2 